spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      bindings:
        userRegistered-out-0:
          destination: user-registered-topic
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

server:
  port: ${SERVER_PORT:8080}

user:
  service:
    url: ${USER_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /auth/swagger-ui
    url: /auth/v3/api-docs
    config-url: /auth/v3/api-docs/swagger-config
  api-docs:
    path: /auth/v3/api-docs
