spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/**
        - id: user-swagger
          uri: ${USER_SWAGGER_URI:http://localhost:8081}
          predicates:
            - Path=/users/swagger-ui/**,/users/v3/api-docs/**
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/auth/**
        - id: auth-swagger
          uri: ${AUTH_SWAGGER_URI:http://localhost:8082}
          predicates:
            - Path=/auth/swagger-ui/**,/auth/v3/api-docs/**
        - id: music-service
          uri: ${MUSIC_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/albums/**,/api/artists/**,/api/genres/**,/api/tracks/**,/api/playlists/**,/api/history/**,/api/queue/**,/api/likes/**,/api/search/**,/api/now-playing/**,/api/library/**
        - id: music-swagger
          uri: ${MUSIC_SWAGGER_URI:http://localhost:8083}
          predicates:
            - Path=/music/swagger-ui/**,/music/v3/api-docs/**

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:myLocalSecretKeyForJWT}
