spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cloud:
    function:
      definition: userRegistered
    stream:
      bindings:
        userRegistered-in-0:
          destination: user-registered-topic
          group: user-service-group
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            back-off-multiplier: 2.0
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
        bindings:
          userRegistered-in-0:
            consumer:
              enable-dlq: true
              dlq-name: user-registered-topic.user-service-group.dlq
              auto-commit-on-error: true

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /user/swagger-ui
    url: /user/v3/api-docs
    config-url: /user/v3/api-docs/swagger-config
  api-docs:
    path: /user/v3/api-docs
